module:cluster:
- sklearn1/cluster/**/*

module:common:
- sklearn1/common/**/*

module:compose:
- sklearn1/compose/**/*

module:covariance:
- sklearn1/covariance/**/*

module:cross_decomposition:
- sklearn1/cross_decomposition/**/*

module:datasets:
- sklearn1/datasets/**/*

module:decomposition:
- sklearn1/decomposition/**/*

module:ensemble:
- sklearn1/ensemble/**/*

module:feature_extraction:
- sklearn1/feature_extraction/**/*

module:feature_selection:
- sklearn1/feature_selection/**/*

module:gaussian_process:
- sklearn1/gaussian_process/**/*

module:impute:
- sklearn1/impute/**/*

module:inspection:
- sklearn1/inspection/**/*

module:linear_model:
- sklearn1/linear_model/**/*

module:manifold:
- sklearn1/manifold/**/*

module:metrics:
- sklearn1/metrics/**/*

module:mixture:
- sklearn1/mixture/**/*

module:model_selection:
- sklearn1/model_selection/**/*

module:naive_bayes:
- sklearn1/naive_bayes.py

module:neighbors:
- sklearn1/neighbors/**/*

module:neural_network:
- sklearn1/neural_network/**/*

module:pipeline:
- sklearn1/pipeline.py

module:preprocessing:
- sklearn1/preprocessing/**/*

module:semi_supervised:
- sklearn1/semi_supervised/**/*

module:svm:
- sklearn1/svm/**/*

module:tree:
- sklearn1/tree/**/*

module:utils:
- sklearn1/utils/**/*
